# ワークフロー名
name: test_chatbot

# 発火タイミング
on:
  # schedule:
  #   - cron: "*/5 * * * *"
  workflow_dispatch

jobs:
  build:
    # Ubuntuの最新版環境内で処理
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール
          pip install matplotlib
          pip install discord
          pip install Pillow
          pip install pandas
          pip install python-dotenv
          pip install sympy
          pip install requests
      - name: Run script
        run: |
          # main.pyの実行
          python main.py
